SELECT
  I1.URL AS "company_logo",
  P1.NAME AS "person_name",
  PS_ERP.TAGS_TO_LITERAL(P2.TAGS) AS "product_tags",
  PP1.CODE AS "productPacking_code",
  PV1.DESCRIPTION AS "productVariant_description",
  COALESCE(SI1.QUANTITY, PSP1.QUANTITY) AS "quantity",
  S1.ID AS "sale_id",
  PS_ERP.TAGS_TO_LITERAL(COALESCE(PLI2.TAGS, PLI1.TAGS)) AS "priceListItem_tags"
FROM
  PS_ERP.PRD_PRODUCTION_ORDER PO1
  INNER JOIN PS_ERP.CAT_COMPANY C1 ON C1.ID = PO1.CAT_COMPANY_ID
  LEFT JOIN PS_ERP.SYS_IMG_IMAGE I1 ON I1.ID = C1.SYS_IMG_IMAGE_ID
  LEFT JOIN PS_ERP.CAT_PERSON P1 ON P1.ID = PO1.CAT_PERSON_ID 
  INNER JOIN PS_ERP.PRD_PRODUCTION_STEP PS1 ON PS1.PRD_PRODUCTION_ORDER_ID = PO1.ID
  INNER JOIN PS_ERP.PRD_PRODUCTION_STEP_PRODUCTION PSP1 ON PSP1.PRD_PRODUCTION_STEP_ID = PS1.ID
  INNER JOIN PS_ERP.CAT_PRODUCT_PACKING PP1 ON PP1.ID = PSP1.CAT_PRODUCT_PACKING_ID
  INNER JOIN PS_ERP.CAT_PRODUCT P2 ON P2.ID = PP1.CAT_PRODUCT_ID
  LEFT JOIN PS_ERP.CAT_PRODUCT_VARIANT PV1 ON PV1.ID = PP1.CAT_PRODUCT_VARIANT_ID
  LEFT JOIN PS_ERP.SAL_SALE S1 ON S1.ID = (PO1.PROPERTIES ->> 'sale_id')::BIGINT
  LEFT JOIN PS_ERP.SAL_SALE_ITEM SI1 ON SI1.SAL_SALE_ID = S1.ID AND SI1.CAT_PRODUCT_PACKING_ID = PSP1.CAT_PRODUCT_PACKING_ID
  LEFT JOIN PS_ERP.COM_PRICE_LIST_ITEM PLI1 ON PLI1.COM_PRICE_LIST_ID = S1.COM_PRICE_LIST_ID AND PLI1.CAT_PRODUCT_ID = P2.ID
  LEFT JOIN PS_ERP.COM_PRICE_LIST_ITEM PLI2 ON PLI2.COM_PRICE_LIST_ID = S1.COM_PRICE_LIST_ID AND PLI2.CAT_PRODUCT_PACKING_ID = PP1.ID
WHERE
  (:PRODUCTION_ORDER_ID::BIGINT IS NULL OR PO1.ID = :PRODUCTION_ORDER_ID::BIGINT)
  AND (:SALE_ID::BIGINT IS NULL OR S1.ID = :SALE_ID::BIGINT)
ORDER BY
  PP1.CODE