SELECT
  I1.URL AS "company_logo",
  S1.ID AS "sale_id",
  P1.NAME AS "person_name",
  PP1.CODE AS "productPacking_code",
  PV1.DESCRIPTION AS "productVariant_description",
  PSP1.QUANTITY AS "quantity",
  CASE
    WHEN PLI1.TAGS ILIKE '%|P|%' THEN 50
    WHEN PLI1.TAGS ILIKE '%|PNB|%' THEN 100
    ELSE NULL
  END AS "units"
FROM
  PS_ERP.PRD_PRODUCTION_ORDER PO1
  INNER JOIN PS_ERP.CAT_COMPANY C1 ON C1.ID = PO1.CAT_COMPANY_ID
  LEFT JOIN PS_ERP.SYS_IMG_IMAGE I1 ON I1.ID = C1.SYS_IMG_IMAGE_ID
  LEFT JOIN PS_ERP.CAT_PERSON P1 ON P1.ID = PO1.CAT_PERSON_ID 
  INNER JOIN PS_ERP.PRD_PRODUCTION_STEP PS1 ON PS1.PRD_PRODUCTION_ORDER_ID = PO1.ID
  INNER JOIN PS_ERP.PRD_PRODUCTION_STEP_PRODUCTION PSP1 ON PSP1.PRD_PRODUCTION_STEP_ID = PS1.ID
  INNER JOIN PS_ERP.CAT_PRODUCT_PACKING PP1 ON PP1.ID = PSP1.CAT_PRODUCT_PACKING_ID
  INNER JOIN PS_ERP.CAT_PRODUCT P2 ON P2.ID = PP1.CAT_PRODUCT_ID
  LEFT JOIN PS_ERP.CAT_PRODUCT_VARIANT PV1 ON PV1.ID = PP1.CAT_PRODUCT_VARIANT_ID
  LEFT JOIN PS_ERP.SAL_SALE S1 ON S1.ID = (PO1.PROPERTIES ->> 'sale_id')::BIGINT
  LEFT JOIN PS_ERP.SAL_SALE_ITEM SI1 ON SI1.SAL_SALE_ID = S1.ID AND SI1.CAT_PRODUCT_PACKING_ID = PSP1.CAT_PRODUCT_PACKING_ID
  LEFT JOIN PS_ERP.COM_PRICE_LIST_ITEM PLI1 ON PLI1.ID = SI1.COM_PRICE_LIST_ITEM_ID
WHERE
  PO1.ID = :PRODUCTION_ORDER_ID
  OR S1.ID = :SALE_ID
