SELECT
  L1.ID AS "id",
  L1.LEVEL AS "level",
  L1.DATETIME AS "dateTime",
  L1.OPERATION AS "operation",
  L1.SOURCE AS "source",
  L1.CONTENT_TYPE AS "contentType",
  L1.CONTENT AS "content",
  L1.EXPIRATION AS "expiration",
  PS_ERP.TAGS_TO_LITERAL(L1.TAGS) AS "tags",
  L1.PROPERTIES AS "properties",
  (L1.PROPERTIES ->> 'ms')::INTEGER AS "properties_ms",
  -- SESSION
  S1.ID AS "session_id",
  -- ROLE
  R1.ID AS "role_id",
  R1.CODE AS "role_code",
  R1.DESCRIPTION "role_description"
FROM
  PS_ERP.SYS_AUD_LOG L1
  LEFT JOIN PS_ERP.SYS_SEC_SESSION S1 ON S1.ID = L1.SYS_SEC_SESSION_ID
  LEFT JOIN PS_ERP.SYS_SEC_ROLE R1 ON R1.ID = S1.SYS_SEC_ROLE_ID 
WHERE
  (:LEVEL_LIST::VARCHAR[] IS NULL OR L1.LEVEL = ANY(:LEVEL_LIST::VARCHAR[]))
  AND (:DATETIME_START::TIMESTAMPTZ IS NULL OR L1.DATETIME >= :DATETIME_START::TIMESTAMPTZ)
  AND (:DATETIME_END::TIMESTAMPTZ IS NULL OR L1.DATETIME <= :DATETIME_END::TIMESTAMPTZ)
  AND (:OPERATION::VARCHAR[] IS NULL OR L1.OPERATION LIKE ANY(:OPERATION::VARCHAR[]))
  AND (:SOURCE::VARCHAR[] IS NULL OR L1.SOURCE LIKE ANY(:SOURCE::VARCHAR[]))
  AND (:EXPIRATION_START::TIMESTAMPTZ IS NULL OR L1.EXPIRATION >= :EXPIRATION_START::TIMESTAMPTZ)
  AND (:EXPIRATION_END::TIMESTAMPTZ IS NULL OR L1.EXPIRATION <= :EXPIRATION_END::TIMESTAMPTZ)
  AND (:TAGS_LIST::VARCHAR[] IS NULL OR PS_ERP.TAGS_TO_ARRAY(LOWER(L1.TAGS)) @> :TAGS_LIST::VARCHAR[])
  AND (:SESSION_IDS::UUID[] IS NULL OR S1.ID = ANY(:SESSION_IDS::UUID[]))
  AND (:ROLE_IDS::BIGINT[] IS NULL OR R1.ID = ANY(:ROLE_IDS::BIGINT[]))
LIMIT
  :LIMIT::INTEGER