SELECT
  V1.CODIGO AS "volume_code",
  N1.ID AS "invoice_id",
  N1.NUMERO AS "invoice_number",
  C2.NOME AS "person_name",
  '' AS "person_address",
  P1.CODIGO AS "product_code",
  P1.DESCRICAO AS "product_description",
  ROW_NUMBER() OVER(PARTITION BY N1.ID ORDER BY V1.CODIGO) AS "item_num",
  COUNT(*) OVER(PARTITION BY N1.ID) AS "item_count"
FROM
  PS_WMS.CARGA C1
  INNER JOIN PS_WMS.NOTA_FISCAL N1 ON N1.CARGA_ID = C1.ID
  INNER JOIN PS_WMS.SEPARACAO_FRAGMENTO SF1 ON SF1.NOTA_FISCAL_ID = N1.ID
  INNER JOIN PS_WMS.VOLUME_LISTA VL1 ON VL1.ID = SF1.VOLUME_LISTA_ID
  INNER JOIN PS_WMS.VOLUME V1 ON V1.VOLUME_LISTA_ID = VL1.ID 
  INNER JOIN PS_WMS.VOLUME_ITEM VI1 ON VI1.VOLUME_ID = V1.ID
  INNER JOIN PS_WMS.ACONDICIONAMENTO A1 ON A1.ID  = VI1.ACONDICIONAMENTO_ID
  INNER JOIN PS_WMS.PRODUTO P1 ON P1.ID = A1.PRODUTO_ID 
  INNER JOIN PS_WMS.CONTA C2 ON C2.ID = N1.CONTA_ID
WHERE
  C1.CODIGO = 2797722
ORDER BY
  N1.NUMERO,
  N1.ID,
  V1.CODIGO