SELECT
  C1.CODIGO AS "carga_codigo",
  C4.NOME AS "carga_transportadora",
  S1.CODIGO AS "ordemSeparacao_codigo",
  V1.CODIGO AS "volume_code",
  N1.ID AS "invoice_id",
  N1.NUMERO AS "invoice_number",
  C2.ID AS "person_id",
  C2.NOME AS "person_name",
  C2.APELIDO AS "person_fantasyName",
  '' AS "person_address",
  C3.NOME AS "person_city",
  C3.ESTADO_SIGLA AS "person_state",
  P1.CODIGO AS "product_code",
  P1.DESCRICAO AS "product_description",
  A1.CODIGO AS "productPacking_code",
  A1.UNIDADES AS "productPacking_units",
  ROW_NUMBER() OVER(PARTITION BY N1.ID, A1.ID ORDER BY V1.CODIGO) AS "product_num",
  COUNT(*) OVER(PARTITION BY N1.ID, A1.ID) AS "product_count",
  ROW_NUMBER() OVER(PARTITION BY N1.ID ORDER BY A1.CODIGO, V1.CODIGO) AS "item_num",
  COUNT(*) OVER(PARTITION BY N1.ID) AS "item_count"
FROM
  PS_WMS.NOTA_FISCAL N1
  INNER JOIN PS_WMS.SEPARACAO_FRAGMENTO SF1 ON SF1.NOTA_FISCAL_ID = N1.ID
  INNER JOIN PS_WMS.ORDEM_SEPARACAO S1 ON S1.ID = SF1.ORDEM_SEPARACAO_ID 
  LEFT JOIN PS_WMS.CARGA C1 ON C1.ID = SF1.CARGA_ID
  INNER JOIN PS_WMS.VOLUME_LISTA VL1 ON VL1.ID = SF1.VOLUME_LISTA_ID
  INNER JOIN PS_WMS.VOLUME V1 ON V1.VOLUME_LISTA_ID = VL1.ID 
  INNER JOIN PS_WMS.VOLUME_ITEM VI1 ON VI1.VOLUME_ID = V1.ID
  INNER JOIN PS_WMS.ACONDICIONAMENTO A1 ON A1.ID  = VI1.ACONDICIONAMENTO_ID
  INNER JOIN PS_WMS.PRODUTO P1 ON P1.ID = A1.PRODUTO_ID 
  LEFT JOIN PS_WMS.CONTA C2 ON C2.ID = N1.CONTA_ID
  LEFT JOIN PS_WMS.CIDADE C3 ON C3.ID = C2.CIDADE_ID
  LEFT JOIN PS_WMS.CONTA C4 ON C4.ID = C1.CONTA_ID_TRANSPORTE
WHERE
  C1.CODIGO = :CODIGO_CARGA
  OR S1.CODIGO = :CODIGO_ORDEM_SEPARACAO
  OR N1.NUMERO = :NUMERO_NOTA_FISCAL
ORDER BY
  A1.CODIGO,
  N1.NUMERO,
  N1.ID,
  V1.CODIGO
